FROM php:8.2-fpm

 
RUN apt-get update && apt-get install -y \
    zip unzip curl git libzip-dev libonig-dev libxml2-dev \
    && docker-php-ext-install pdo pdo_mysql zip

 
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer 
WORKDIR /var/www 
COPY . . 
RUN composer install --no-interaction --no-dev --prefer-dist 
RUN chown -R www-data:www-data /var/www && chmod -R 755 /var/www

EXPOSE 9000
CMD ["php-fpm"]
